#!/bin/bash

# Script de Guía Visual para Prueba Manual
# Uso: bash prueba_visual.sh

clear

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║         🧪 JOBFACTORY - GUÍA DE PRUEBA MANUAL 🧪              ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Esta guía te ayudará a probar la aplicación paso a paso."
echo "Presiona ENTER para continuar en cada sección."
echo ""

# Paso 1
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 1: VERIFICACIÓN INICIAL                                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Checklist:"
echo "   [ ] Hardhat está corriendo en http://localhost:8545"
echo "   [ ] Frontend está corriendo en http://localhost:3000"
echo "   [ ] MetaMask está instalada en el navegador"
echo "   [ ] MetaMask está configurada en Localhost 8545 (Chain ID: 31337)"
echo ""
echo "Abre una terminal y verifica:"
echo "   curl http://localhost:8545"
echo "   curl http://localhost:3000"
echo ""
read -p "¿Listo? Presiona ENTER para continuar..."
clear

# Paso 2
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 2: CONECTAR WALLET                                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Conectar MetaMask a la aplicación"
echo ""
echo "Instrucciones:"
echo "   1. Abre http://localhost:3000 en el navegador"
echo "   2. Busca el botón 'Conectar Wallet' en la esquina superior derecha"
echo "   3. Haz clic en él"
echo "   4. MetaMask se abrirá pidiendo permisos"
echo "   5. Haz clic en 'Siguiente' → 'Conectar'"
echo ""
echo "✅ Verificación:"
echo "   [ ] El botón cambió a VERDE"
echo "   [ ] Muestra tu address truncada (0x5f73...d7c7)"
echo "   [ ] Hay un punto pulsante verde"
echo ""
read -p "¿El wallet está conectado? Presiona ENTER para continuar..."
clear

# Paso 3
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 3: PUBLICAR UN TRABAJO (ROL: CLIENTE)                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Publicar tu primer trabajo"
echo ""
echo "Instrucciones:"
echo "   1. Haz clic en botón '+ Publicar trabajo'"
echo "   2. Llena el formulario con:"
echo ""
echo "      Título: Crear API REST con Node.js"
echo "      Descripción: API con autenticación JWT y MongoDB"
echo "      Presupuesto: 2.5"
echo "      Fecha: Elige un día futuro (ej: mañana)"
echo ""
echo "   3. Haz clic en '🚀 Publicar trabajo'"
echo "   4. MetaMask pide confirmación → Confirma"
echo ""
echo "✅ Verificación:"
echo "   [ ] El formulario se cierra automáticamente"
echo "   [ ] El trabajo aparece en 'Trabajos disponibles'"
echo "   [ ] Estado es '⏳ Pendiente' (header amarillo)"
echo "   [ ] Presupuesto muestra 'Ξ 2.5 ETH'"
echo ""
read -p "¿El trabajo se publicó? Presiona ENTER para continuar..."
clear

# Paso 4
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 4: VER PANEL DE CLIENTE                                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Verificar el panel de cliente"
echo ""
echo "Instrucciones:"
echo "   1. Haz clic en '📊 Panel de cliente'"
echo "   2. O accede directamente a http://localhost:3000/client"
echo ""
echo "✅ Verificación:"
echo "   [ ] Total publicados: 1"
echo "   [ ] Pendientes: 1"
echo "   [ ] Aceptados: 0"
echo "   [ ] Cancelados: 0"
echo "   [ ] Tu trabajo aparece en 'Mis trabajos'"
echo ""
read -p "¿El panel se ve correcto? Presiona ENTER para continuar..."
clear

# Paso 5
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 5: CAMBIAR A CUENTA DE FREELANCER                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Cambiar a una cuenta diferente para simular freelancer"
echo ""
echo "Instrucciones:"
echo "   1. En MetaMask, haz clic en tu account"
echo "   2. Selecciona o crea una NUEVA CUENTA"
echo "   3. O selecciona una account diferente de la que creó el trabajo"
echo "   4. Recarga la página (F5)"
echo ""
echo "⚠️ Importante:"
echo "   - Debe ser una cuenta diferente a la que creó el trabajo"
echo "   - Así simulamos a un freelancer diferente"
echo ""
echo "✅ Verificación:"
echo "   [ ] MetaMask muestra una dirección diferente"
echo "   [ ] La página se ha recargado"
echo ""
read -p "¿Ya eres freelancer? Presiona ENTER para continuar..."
clear

# Paso 6
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 6: VER PANEL DE FREELANCER                               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Ver los trabajos disponibles como freelancer"
echo ""
echo "Instrucciones:"
echo "   1. Haz clic en '👨‍💼 Panel de freelancer'"
echo "   2. O accede a http://localhost:3000/freelancer"
echo ""
echo "✅ Verificación:"
echo "   [ ] Trabajos aceptados: 0"
echo "   [ ] Disponibles: 1"
echo "   [ ] Ingresos potenciales: Ξ 0"
echo "   [ ] El trabajo publicado aparece en 'Trabajos disponibles para aceptar'"
echo ""
read -p "¿Ves los trabajos disponibles? Presiona ENTER para continuar..."
clear

# Paso 7
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 7: ACEPTAR UN TRABAJO                                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Aceptar el trabajo publicado"
echo ""
echo "Instrucciones:"
echo "   1. En 'Trabajos disponibles para aceptar', busca tu trabajo"
echo "   2. Haz clic en el botón 'Aceptar trabajo'"
echo "   3. MetaMask pide confirmación → Confirma"
echo ""
echo "✅ Verificación:"
echo "   [ ] MetaMask muestra la transacción"
echo "   [ ] El trabajo desaparece de 'Trabajos disponibles'"
echo "   [ ] Recarga la página (F5)"
echo "   [ ] El trabajo ahora está en 'Mis trabajos en progreso'"
echo "   [ ] Estado cambió a '✅ Aceptado' (header verde)"
echo ""
read -p "¿Aceptaste el trabajo? Presiona ENTER para continuar..."
clear

# Paso 8
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 8: PRUEBAR FILTROS                                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Verificar que los filtros funcionan correctamente"
echo ""
echo "Instrucciones:"
echo "   1. Vuelve a la página principal (http://localhost:3000)"
echo "   2. Busca los botones de filtro: Todos | Pendientes | Aceptados | Cancelados"
echo "   3. Haz clic en cada uno y verifica:"
echo ""
echo "      - 'Todos (📋)': Muestra TODOS los trabajos"
echo "      - 'Pendientes (⏳)': Muestra solo los pendientes"
echo "      - 'Aceptados (✅)': Muestra solo los aceptados (deberías ver 1)"
echo "      - 'Cancelados (❌)': Muestra solo cancelados (0 en este caso)"
echo ""
echo "✅ Verificación:"
echo "   [ ] Cada filtro funciona correctamente"
echo "   [ ] Los botones activos tienen fondo azul"
echo "   [ ] Hay un contador con el número de trabajos"
echo ""
read -p "¿Los filtros funcionan? Presiona ENTER para continuar..."
clear

# Paso 9
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 9: VALIDACIONES DEL FORMULARIO                           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Verificar que el formulario valida correctamente"
echo ""
echo "Instrucciones:"
echo "   1. Haz clic en '+ Publicar trabajo'"
echo "   2. Intenta enviar SIN llenar nada"
echo "      ❌ Error: 'El título es requerido'"
echo ""
echo "   3. Llena solo el título"
echo "      ❌ Error: 'La descripción es requerida'"
echo ""
echo "   4. Llena título y descripción, pero presupuesto = 0"
echo "      ❌ Error: 'El presupuesto debe ser mayor a 0'"
echo ""
echo "   5. Todo lleno pero fecha en el pasado"
echo "      ❌ Error: 'La fecha de entrega debe ser en el futuro'"
echo ""
echo "✅ Verificación:"
echo "   [ ] Todos los mensajes de error aparecen en ROJO"
echo "   [ ] Los mensajes son claros y útiles"
echo ""
read -p "¿Las validaciones funcionan? Presiona ENTER para continuar..."
clear

# Paso 10
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 10: VERIFICACIÓN VISUAL                                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Verificar que la UI se ve profesional"
echo ""
echo "Checklist Visual:"
echo ""
echo "   Header:"
echo "      [ ] Logo 'JF' con gradiente azul"
echo "      [ ] Header es sticky (se queda arriba al scroll)"
echo "      [ ] Botón de wallet en esquina derecha"
echo ""
echo "   Hero Section:"
echo "      [ ] Fondo con gradiente azul (blue-600 → blue-800)"
echo "      [ ] Título grande 'JobFactory'"
echo "      [ ] Descripción clara"
echo ""
echo "   Cards de Estadísticas:"
echo "      [ ] Tienen emojis (📊 ✅ ⏳)"
echo "      [ ] Al pasar el mouse, la sombra aumenta"
echo "      [ ] Números grandes y en color"
echo ""
echo "   JobCards:"
echo "      [ ] Header con color según estado:"
echo "         - Amarillo para '⏳ Pendiente'"
echo "         - Verde para '✅ Aceptado'"
echo "         - Rojo para '❌ Cancelado'"
echo "      [ ] Presupuesto visible con símbolo Ξ"
echo "      [ ] Fecha de entrega visible"
echo "      [ ] Dirección del cliente en fondo gris"
echo "      [ ] Botones con hover effects"
echo ""
echo "   Formulario:"
echo "      [ ] Campos con bordes azules en focus"
echo "      [ ] Contador de caracteres visible"
echo "      [ ] Botón rojo para error, azul para envío"
echo "      [ ] Error messages en rojo"
echo ""
echo "   Botones:"
echo "      [ ] Primarios: Azul (hover: azul más oscuro)"
echo "      [ ] Secundarios: Blanco con borde gris"
echo "      [ ] Todos tienen transiciones suaves"
echo ""
read -p "¿La UI se ve profesional? Presiona ENTER para finalizar..."
clear

# Paso 11
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ PASO 11: DESCONEXIÓN Y ACCESO RESTRINGIDO                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Objetivo: Verificar que el acceso sin wallet funciona"
echo ""
echo "Instrucciones:"
echo "   1. Haz clic en el botón de wallet (verde, muestra tu address)"
echo "   2. Busca la opción 'Desconectar'"
echo "   3. Haz clic"
echo ""
echo "✅ Verificación Paso 1:"
echo "   [ ] El botón vuelve a ser AZUL"
echo "   [ ] Muestra 'Conectar MetaMask'"
echo "   [ ] Desaparece el punto pulsante"
echo ""
echo "   4. Ahora intenta acceder a http://localhost:3000/client"
echo ""
echo "✅ Verificación Paso 2:"
echo "   [ ] Ves pantalla 'Acceso restringido' 🔒"
echo "   [ ] Dice 'Por favor conecta tu wallet para acceder'"
echo "   [ ] Hay un botón '← Volver al inicio'"
echo ""
echo "   5. Lo mismo aplica para http://localhost:3000/freelancer"
echo ""
read -p "¿El acceso restringido funciona? Presiona ENTER para terminar..."
clear

# Resumen final
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║                  ✅ PRUEBA COMPLETADA ✅                      ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Resumen de Pruebas:"
echo ""
echo "   ✅ Conectar wallet"
echo "   ✅ Publicar trabajo"
echo "   ✅ Panel de cliente"
echo "   ✅ Panel de freelancer"
echo "   ✅ Aceptar trabajo"
echo "   ✅ Filtros"
echo "   ✅ Validaciones"
echo "   ✅ Visual/UI"
echo "   ✅ Acceso restringido"
echo ""
echo "🎉 ¡Tu aplicación está funcionando correctamente!"
echo ""
echo "Próximos pasos:"
echo "   - Implementar JobDetail.js para vista completa"
echo "   - Implementar EscrowActions.js para escrow"
echo "   - Agregar más trabajos para pruebas más complejas"
echo "   - Probar en múltiples dispositivos"
echo ""
echo "Documentación:"
echo "   - PRUEBA_MANUAL.md: Guía detallada"
echo "   - QUICK_TEST.md: Resumen rápido"
echo "   - UI_IMPROVEMENTS.md: Detalles de diseño"
echo ""
